#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: aa
#    password:
#    driver-class-name: org.h2.Driver
#
#jpa:
#  hibernate:
#    ddl-auto: create
#  properties:
#    hibernate:
#      #show_sql : true JPA가 실행하는 쿼리를 모두 찍는다. 콘솔에
#      format_sql: true
#
#logging.level:
#  level:
#    org.hibernate.SQL: debug
##    org.hibernate.type : trace

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: aa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true

  # Page를 글로벌하게 설정할 수 있다.
  data:
    web:
      pageable:
        default-age-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true 1부터 시작하게 하는 옵션 (default = false)
        # 해당 방법은 설정 property의 값이 맞지않아, 문제가 있다.
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace